services:
  - type: web
    name: omid-ataei-support-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_USER_ID
        sync: false
      - key: INSTAGRAM_APP_SECRET
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: PORT
        value: 3000